Repository google/s2a-go, pull requests merged in 2022-05, with the labels that each got.

#11 Add S2Av2 proto files.
  internal/proto/v2/BUILD
  internal/proto/v2/common.proto
  internal/proto/v2/common_go_proto/BUILD
  internal/proto/v2/common_go_proto/common.pb.go
  internal/proto/v2/s2a.proto
  internal/proto/v2/s2a_context.proto
  internal/proto/v2/s2a_context_go_proto/BUILD
  internal/proto/v2/s2a_context_go_proto/s2a_context.pb.go
  internal/proto/v2/s2a_go_proto/BUILD
  internal/proto/v2/s2a_go_proto/s2a.pb.go
  internal/proto/v2/s2a_go_proto/s2a_grpc.pb.go
  tools/proto/regenerate_proto.sh
Labels: build

#12 Update README.
  README.md
Labels: documentation

#13 Fix typos in //internal/proto/v2/s2a.proto.
  internal/proto/v2/s2a.proto
  internal/proto/v2/s2a_go_proto/s2a.pb.go
Labels: documentation

#14 Minor updates to the S2Av2 proto.
  internal/proto/v2/s2a.proto
  internal/proto/v2/s2a_go_proto/s2a.pb.go
Labels: documentation, cleanup

#16 Add README for internal v2 directory
  internal/v2/README.md
Labels: feature request

#17 Update go.mod to 1.16 to support go:embed
  go.mod
Labels: feature request

#19 Update Golang version on MacOS when running Kokoro tests.
  tools/internal_ci/run_golang_tests.sh
Labels: bug

#21 Update S2A context proto with local identity and credentials info.
  internal/proto/v2/BUILD
  internal/proto/v2/s2a_context.proto
  internal/proto/v2/s2a_context_go_proto/BUILD
  internal/proto/v2/s2a_context_go_proto/s2a_context.pb.go
  tools/proto/regenerate_proto.sh
Labels: feature request

#18 Static TLS Configuration Store Library Implementation
  internal/v2/tls_config_store/BUILD
  internal/v2/tls_config_store/example_cert_key/client_cert.pem
  internal/v2/tls_config_store/example_cert_key/client_key.pem
  internal/v2/tls_config_store/example_cert_key/server_cert.pem
  internal/v2/tls_config_store/example_cert_key/server_key.pem
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request

#22 Static implementation of Remote Signer Library
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/example_cert_key/cert.pem
  internal/v2/remote_signer/example_cert_key/key.pem
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
Labels: feature request

#23 New example certificates with 20 year lifetime
  internal/v2/cert_verifier/example_cert_key/client_cert.pem
  internal/v2/cert_verifier/example_cert_key/client_key.pem
  internal/v2/cert_verifier/example_cert_key/server_cert.pem
  internal/v2/cert_verifier/example_cert_key/server_key.pem
  internal/v2/remote_signer/example_cert_key/cert.pem
  internal/v2/remote_signer/example_cert_key/key.pem
  internal/v2/remote_signer/remote_signer_test.go
  internal/v2/tls_config_store/example_cert_key/client_cert.pem
  internal/v2/tls_config_store/example_cert_key/client_key.pem
  internal/v2/tls_config_store/example_cert_key/server_cert.pem
  internal/v2/tls_config_store/example_cert_key/server_key.pem
Labels: cleanup
