Repository google/s2a-go, pull requests merged in 2022-07, with the labels that each got.

#55 Manage token in Fake S2Av2
  internal/v2/fakes2av2/BUILD
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/example_cert_key/client_cert.der
  internal/v2/remote_signer/example_cert_key/client_cert.pem
  internal/v2/remote_signer/example_cert_key/client_key.pem
  internal/v2/remote_signer/example_cert_key/server_cert.der
  internal/v2/remote_signer/example_cert_key/server_cert.pem
  internal/v2/remote_signer/example_cert_key/server_key.pem
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
  s2a_e2e_test.go
Labels: feature request

#56 Check resp.GetStatus() before accessing Code
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/remote_signer/remote_signer.go
  internal/v2/tls_config_store/tls_config_store.go
Labels: feature request

#61 Fix go vet and gofmt errors.
  example/client/client.go
  example/server/server.go
  go.mod
  go.sum
  internal/fakehandshaker/service/s2a_service_test.go
  internal/handshaker/handshaker.go
  internal/handshaker/handshaker_test.go
  internal/record/internal/halfconn/halfconn.go
  internal/record/record.go
  internal/record/record_test.go
  internal/record/ticketsender.go
  internal/record/ticketsender_test.go
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/cert_verifier/cert_verifier_test.go
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/fakes2av2_server/fakes2av2_server.go
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
  internal/v2/s2av2.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/s2av2_test.go
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
  s2a.go
  s2a_e2e_test.go
  s2a_options_test.go
  s2a_test.go
  tools/internal_ci/run_hygiene_tests.sh
Labels: cleanup

#57 Populate localIdentity in first SessionReq.
  example/client/BUILD
  example/client/client.go
  example/server/BUILD
  example/server/server.go
  internal/v2/BUILD
  internal/v2/s2av2.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/s2av2_test.go
  internal/v2/tls_config_store/tls_config_store.go
  s2a.go
Labels: feature request

#59 Add VerificationMode to ValidatePeerCertificateChainReq SessionReq
  BUILD
  example/client/BUILD
  example/client/client.go
  example/server/BUILD
  example/server/server.go
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/cert_verifier/cert_verifier_test.go
  internal/v2/s2av2.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/s2av2_test.go
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
  s2a.go
  s2a_options.go
  s2a_test.go
Labels: feature request

#60 Mapping to all S2A Signature Algorithms
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
Labels: feature request

#63 Update V2 s2a.proto to specify in_bytes
  internal/proto/v2/s2a.proto
  internal/proto/v2/s2a_go_proto/s2a.pb.go
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
Labels: feature request

#68 Improve Readability
  internal/v2/s2av2.go
  internal/v2/testdata/README.md
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
  s2a.go
  s2a_options.go
  s2a_test.go
Labels: cleanup

#70 Continue creating transport creds when tokenManager is nil.
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/s2av2.go
  internal/v2/tls_config_store/tls_config_store_test.go
  s2a_e2e_test.go
Labels: bug

#71 Add logging in production code.
  internal/v2/BUILD
  internal/v2/cert_verifier/BUILD
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/remote_signer.go
  internal/v2/s2av2.go
  internal/v2/tls_config_store/tls_config_store.go
Labels: feature request

#72 Add NextProtos field to TLS config.
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request
