Repository google/s2a-go, pull requests merged in 2022-06, with the labels that each got.

#24 Transport Credentials Interface implementation
  internal/v2/BUILD
  internal/v2/s2av2.go
  internal/v2/s2av2_test.go
  internal/v2/tls_config_store/BUILD
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request

#25 Cleanup output s2a.go
  s2a.go
Labels: cleanup

#26 Remove port from serverAuthority
  internal/v2/s2av2.go
  internal/v2/s2av2_test.go
Labels: feature request

#36 Add binary files to .gitignore
  .gitignore
Labels: feature request

#32 Improve fakes2av2 test suite
  internal/v2/fakes2av2/fakes2av2_test.go
Labels: cleanup, feature request

#39 Don't set RootCAs / ClientCAs in TLS Config Store
  internal/v2/tls_config_store/tls_config_store.go
Labels: feature request

#41 Add documentation about how example certificates and keys are generated
  internal/v2/README.md
  internal/v2/testdata/README.md
Labels: documentation

#38 Fake Implementation of offloadPrivateKeyOperation
  internal/v2/fakes2av2/BUILD
  internal/v2/fakes2av2/example_cert_key/client_root_cert.der
  internal/v2/fakes2av2/example_cert_key/client_root_cert.pem
  internal/v2/fakes2av2/example_cert_key/client_root_key.pem
  internal/v2/fakes2av2/example_cert_key/server_root_cert.der
  internal/v2/fakes2av2/example_cert_key/server_root_cert.pem
  internal/v2/fakes2av2/example_cert_key/server_root_key.pem
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
Labels: feature request

#42 Remote Signer makes RPC to Fake S2Av2
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/example_cert_key/cert.der
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
Labels: feature request

#43 Populate ClientCAs field in Server TLS config
  internal/v2/tls_config_store/tls_config_store.go
Labels: bug, feature request

#44 Remove InsecureSkipVerify from server TLS config
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: cleanup

#49 Add end to end integration tests to use S2Av2 client
  internal/v2/BUILD
  internal/v2/s2av2_e2e_test.go
Labels: feature request

#52 Add initial scripts and configs for Kokoro hygiene tests.
  kokoro/gcp_ubuntu/continuous_hygiene.cfg
  kokoro/gcp_ubuntu/kokoro_hygiene.sh
  kokoro/gcp_ubuntu/presubmit_hygiene.cfg
  tools/internal_ci/run_hygiene_tests.sh
Labels: testing

#50 Handle SessionResp Status field in Cert Verifier
  internal/v2/cert_verifier/BUILD
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/cert_verifier/cert_verifier_test.go
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
Labels: feature request

#46 Call the token manager for authentication mechanism
  internal/v2/BUILD
  internal/v2/cert_verifier/BUILD
  internal/v2/cert_verifier/cert_verifier.go
  internal/v2/cert_verifier/cert_verifier_test.go
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
  internal/v2/s2av2.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/s2av2_test.go
  internal/v2/tls_config_store/BUILD
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request

#51 Handle SessionResp Status field in Remote Signer
  internal/v2/fakes2av2/BUILD
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/remote_signer/BUILD
  internal/v2/remote_signer/remote_signer.go
  internal/v2/remote_signer/remote_signer_test.go
Labels: feature request

#48 Use Go-gRPC status code constants
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
Labels: feature request

#53 Add V2 flag to S2A options
  BUILD
  internal/v2/fakes2av2/BUILD
  s2a.go
  s2a_e2e_test.go
  s2a_options.go
Labels: feature request

#47 Add GetConfigForClient field to Server TLS Config
  internal/v2/remote_signer/remote_signer.go
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request

#54 Map tls.ClientAuthType to s2av2 proto RequestClientCertificate
  example/proto/echo_go_proto/echo.pb.go
  example/proto/echo_go_proto/echo_grpc.pb.go
  internal/proto/common_go_proto/common.pb.go
  internal/proto/examples/helloworld_go_proto/helloworld.pb.go
  internal/proto/examples/helloworld_go_proto/helloworld_grpc.pb.go
  internal/proto/s2a_context_go_proto/s2a_context.pb.go
  internal/proto/s2a_go_proto/s2a.pb.go
  internal/proto/s2a_go_proto/s2a_grpc.pb.go
  internal/proto/v2/common_go_proto/common.pb.go
  internal/proto/v2/s2a.proto
  internal/proto/v2/s2a_context_go_proto/s2a_context.pb.go
  internal/proto/v2/s2a_go_proto/s2a.pb.go
  internal/proto/v2/s2a_go_proto/s2a_grpc.pb.go
  internal/v2/fakes2av2/fakes2av2.go
  internal/v2/fakes2av2/fakes2av2_test.go
  internal/v2/tls_config_store/tls_config_store.go
  internal/v2/tls_config_store/tls_config_store_test.go
Labels: feature request
