Repository google/s2a-go, pull requests merged in 2023-01, with the labels that each got.

#84 expose public method to generate a s2a-enabled tls configuration
  BUILD
  internal/v2/BUILD
  internal/v2/s2av2.go
  internal/v2/s2av2_e2e_test.go
  internal/v2/tlsconfigstore/example_cert_key/BUILD
  s2a.go
  s2a_e2e_test.go
Labels: feature request

#86 Add support for AppEngine-specific dialer.
  WORKSPACE
  go.mod
  go.sum
  internal/handshaker/service/BUILD
  internal/handshaker/service/service.go
Labels: feature request

#87 Remove enable_appengine_dialer flag.
  internal/handshaker/service/service.go
Labels: bug

#88 Reintroduce flag that guards AppEngine-specific dialer.
  internal/handshaker/service/service.go
  internal/handshaker/service/service_test.go
Labels: cleanup
